name: Bug Report
description: File a bug report to help us improve Steam Cookie Searcher.
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please provide as much detail as possible.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Steam Cookie Searcher are you using? (e.g., 0.0.1)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS did you experience the bug on?
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run the app
        2. Press '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please upload screenshots of the bug or error.
